### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by mphcomputing** [eligible/knife-bastion#10]
After starting knife bastion, any command (including knife bastion status) gives an EOF error. I have been able to get the following stacktrace:
```Traceback (most recent call last):
	29: from /usr/local/bin/knife:353:in `<main>'
	28: from /usr/local/bin/knife:353:in `load'
	27: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/bin/knife:24:in `<top (required)>'
	26: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/application/knife.rb:163:in `run'
	25: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/knife.rb:229:in `run'
	24: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	23: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	22: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/knife.rb:486:in `block in run_with_pretty_exceptions'
	21: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/knife/node_list.rb:39:in `run'
	20: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/node.rb:597:in `list'
	19: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:115:in `get'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:149:in `request'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:368:in `send_http_request'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:412:in `retrying_http_errors'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:412:in `loop'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:414:in `block in retrying_http_errors'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http.rb:375:in `block in send_http_request'
	12: from /Users/mike.marchese/.chefdk/gem/ruby/2.6.0/gems/knife-bastion-1.2.0/lib/knife-bastion/client_proxy.rb:50:in `method_missing'
	11: from /Users/mike.marchese/.chefdk/gem/ruby/2.6.0/gems/knife-bastion-1.2.0/lib/knife-bastion/client_proxy.rb:59:in `with_socks_proxy'
	10: from /Users/mike.marchese/.chefdk/gem/ruby/2.6.0/gems/knife-bastion-1.2.0/lib/knife-bastion/client_proxy.rb:51:in `block in method_missing'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/http/basic_client.rb:69:in `request'
	 8: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	 7: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http.rb:919:in `start'
	 6: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	 5: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http.rb:969:in `connect'
	 4: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
	 3: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
	 2: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
	 1: from /opt/chefdk/embedded/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/opt/chefdk/embedded/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)```

**Comment by mphcomputing** [comment]
Disregard. It was an issue with an local env setting
